plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.darkonly.dvdbattleultimate'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.darkonly.dvdbattleultimate"
        minSdk 23
        targetSdk 37
        versionCode 4
        versionName "1.6"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    implementation libs.play.services.nearby
    implementation libs.okhttp
    implementation "androidx.multidex:multidex:2.0.1"
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}